package my.edu.tarc.dco.bookrentalpos;

import java.sql.ResultSet;
import java.sql.SQLException;

public class BookManager {

    private Book[] bookList;
    private int bookCount;
    private DBManager db;
    private final int ARRAY_SIZE = 100;

    public BookManager(DBManager db) {
	bookCount = 0;
	bookList = new Book[ARRAY_SIZE];
	this.db = db;
	String sql = "SELECT * FROM book;";
	try {
	    java.sql.ResultSet rs = db.resultQuery(sql);
	    while (rs.next()) {		
		Book s = new Book(
			rs.getInt("id"),
			rs.getString("title"),
			rs.getString("date"),
			rs.getDouble("rentalPrice"),
			rs.getInt("lastRentedBy"),
			rs.getInt("lastReservedBy")
		);
		bookList[bookCount++] = s;
	    }
	} catch (java.sql.SQLException err) {
	    System.out.println(err.getMessage());
	}
    }

    public Book getbook(int bookID) {
	for (int i = 0; i < bookCount; i++) {
	    if (bookList[i].getID() == bookID) {
		return bookList[i];
	    }
	}
	return null;
    }

    public boolean addBook(Book book) {
	String sql = String.format("INSERT INTO book(title, rentalPrice, lastRentedBy, lastReservedBy) VALUES('%s', '%f', %s, %s)",
		book.getName(),
		book.getRentalPrice(),
		book.getLastRentedBy() == 0 ? "null" : book.getLastRentedBy() + "",
		book.getLastReservedBy() == 0 ? "null" : book.getLastReservedBy() + ""
	);
	if (db.updateQuery(sql) == 1) {
	    try {
		// id and date is generated by sqlite, i need to make a copy of it and store it in my preloaded database
		// this query basically get the latest Mmeber entry inserted into database
		ResultSet rs = db.resultQuery("SELECT id, date FROM book WHERE id = (SELECT seq FROM sqlite_sequence WHERE name='book')");
		book.setID(rs.getInt("id"));
		book.setDateCreated(rs.getString("date"));

		// store in my preloaded database
		bookList[bookCount++] = book;
	    } catch (SQLException err) {
		System.out.println(err.getMessage());
	    }
	    return true;
	} else {
	    return false;
	}
    }

    public boolean updateBook(Book bk) {
	if (bk.getID() == 0) {
	    return false;
	}
	String sql = String.format("UPDATE book\n"
		+ "SET title='%s', rentalPrice=%f, lastRentedBy=%s, lastReservedBy=%s\n"
		+ "WHERE id=%d;",
		bk.getName(),
		bk.getRentalPrice(),
		bk.getLastRentedBy() == 0 ? "null" : bk.getLastRentedBy() + "",
		bk.getLastReservedBy() == 0 ? "null" : bk.getLastReservedBy() + "",
		bk.getID());
	if (db.updateQuery(sql) == 1) {
	    return true;
	}
	return false;
    }

    public boolean removebBook(int bookID) {
	String sql = String.format("DELETE FROM book WHERE id=%d", bookID);
	Book[] tmpList = new Book[ARRAY_SIZE];
	if (db.updateQuery(sql) == 1) {
	    int b = 0;
	    for (int a = 0; a < bookCount; a++) {
		if (bookList[a].getID() != bookID) {
		    tmpList[b++] = bookList[a];
		}
	    }
	    bookList = tmpList.clone();
	    bookCount--;
	    return true;
	} else {
	    return false;
	}
    }

}
