package my.edu.tarc.dco.bookrentalpos;

/**
 * Parent class of all entity in POS system
 *
 * @author Looz
 * @version 1.0
 */
public class Entity {

    private int id;
    private String name;
    private String dateCreated;

    /**
     * Blank
     */
    public Entity() {

    }

    /**
     * Constructor to initialise Entity
     * @param id - can be 0 if you wish not to initialise it
     * @param name - can be null if u wish not to intialise
     * @param dateCreated - can be null if u wish not to intialise
     */
    public Entity(int id, String name, String dateCreated) {
        this.id = id;
        this.name = name;
        this.dateCreated = dateCreated;
    }

    /**
     * Overridden equals() method to check against id of the entity
     * @param obj Can be integer indicating id
     * @return true if the id matches
     */
    @Override
    public boolean equals(Object obj) {
        if(obj instanceof Entity) {
            return getId() == ((Entity) obj).getId();
        }
        return super.equals(obj);
    }

    /**
     * @return ID of the entity, usually generated by database
     */
    public final int getId() {
	return this.id;
    }

    /**
     *
     * @return name of the entity
     */
    public final String getName() {
	return this.name;
    }

    /**
     *
     * @return date the entity was created in database, usually generated by
     * database
     */
    public final String getDateCreated() {
	return this.dateCreated;
    }

    /**
     * This function shouldn't be used except for initialization purpose
     *
     * @param id id of the entity
     */
    public final void setID(int id) {
	this.id = id;
    }

    /**
     * @param name name of the entity
     */
    public final void setName(String name) {
	this.name = name;
    }

    /**
     * This function shouldn't be used except for initialization purpose
     *
     * @param date creation date of the entity in database
     */
    public final void setDateCreated(String date) {
	this.dateCreated = date;
    }
}
