package my.edu.tarc.dco.bookrentalpos;

/**
 * Class to hold member data
 *
 * @author Looz
 * @version 1.0
 */
public class Member extends Entity {

    private String phoneNo;
    private String email;
    private String icNo;
    private int memberPoints;

    /**
     * Blank
     */
    public Member() {

    }

    /**
     * Constructor to create a new member without contacts
     *
     * @param icNo NRIC number of the member
     * @param name Name of the member
     */
    public Member(String icNo, String name) {
        super(0, name, null);
        this.icNo = icNo;
        this.phoneNo = "";
        this.email = "";
        this.memberPoints = 0;
    }

    /**
     * Constructor to create a new member with contacts
     *
     * @param icNo    NRIC number of the member
     * @param name    Name of the member
     * @param phoneNo Phone number of the member
     * @param email   Email of the member
     * @see Member#Member(java.lang.String, java.lang.String)
     */
    public Member(String icNo, String name, String phoneNo, String email) {
        super(0, name, null);
        this.icNo = icNo;
        this.phoneNo = phoneNo;
        this.email = email;
        this.memberPoints = 0;
    }

    /**
     * Constructor used to import data from database, DO NOT use it to create
     * new member
     *
     * @param id           memberID generated by database
     * @param date         creation date of the member in database
     * @param name         Name of the member
     * @param phoneNo      Phone number of the member
     * @param email        Email of the member
     * @param icNo         NRIC number of the member
     * @param memberPoints member points they get from returning books in time
     * @see Member#Member(java.lang.String, java.lang.String, java.lang.String,
     * java.lang.String)
     */
    public Member(int id, String date, String name, String phoneNo, String email, String icNo, int memberPoints) {
        super(id, name, date);
        this.phoneNo = phoneNo;
        this.email = email;
        this.icNo = icNo;
        this.memberPoints = memberPoints;
    }

    @Override
    public String toString() {
        return String.format(
                "Name: %s\nNRIC: %s\nPhone No.: %s\nEmail: %s\nPoints: %d",
                this.getName(),
                this.getIcNo(),
                this.getPhoneNo(),
                this.getEmail(),
                this.getMemberPoints()
        );
    }

    /**
     * @param ic set NRIC in string
     */
    public void setIcNo(String ic) {
        this.icNo = ic;
    }

    public void setPhoneNo(String phone) {
        this.phoneNo = phone;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public int getMemberPoints() {
        return memberPoints;
    }

    // ============================================================================================================
    // Functions below this point is for the PropertyValueFactory in JavaFx to fetch data from this class
    // ============================================================================================================

    /**
     * @return NRIC of the member
     */
    public String getIcNo() {
        return this.icNo;
    }

    public String getPhoneNo() {
        return this.phoneNo;
    }

    public String getEmail() {
        return this.email;
    }

    public void setMemberPoints(int memberPoints) {
        this.memberPoints = memberPoints;
    }
}
