package my.edu.tarc.dco.bookrentalpos;

import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Looz
 */
public class TransactionManager {

    private Transaction[] transactionList;
    private final int ARRAY_SIZE = 100;
    private DBManager db;
    private int transactionCount;

    public TransactionManager(DBManager db) {
	this.db = db;
	transactionCount = 0;
	transactionList = new Transaction[ARRAY_SIZE];
    }

    // this function accepts transaction object where there is no id and date
    public boolean addTransaction(Transaction trans) {
	String sql = String.format(
		"INSERT INTO transactions(type, staffHandled, memberInvolved, bookInvolved, rentDurationInDays) VALUES('%s',%d,%d,%d,%d)",
		trans.getType(),
		trans.getStaffHandled().getID(),
		trans.getMemberInvovled().getID(),
		trans.getBookInvovled().getID(),
		trans.getRentDurationInDays());
	if (db.updateQuery(sql) == 1) {
	    try {
		// id and date is generated by sqlite, i need to make a copy of it and store it in my preloaded database
		// this query basically get the latest Mmeber entry inserted into database
		ResultSet rs = db.resultQuery("SELECT id, date FROM member WHERE id = (SELECT seq FROM sqlite_sequence WHERE name='transactions')");
		trans.setID(rs.getInt("id"));
		trans.setDateCreated(rs.getString("date"));

		// store in my preloaded database
		transactionList[transactionCount++] = trans;
	    } catch (SQLException err) {
		System.out.println(err.getMessage());
	    }
	    return true;
	} else {
	    return false;
	}
    }
}
